version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000-3004:3000"
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    volumes:
      - ./api:/app
    working_dir: /app
    depends_on:
      - db
    deploy:
      replicas: 5
