openapi: 3.0.1
info:
  title: Event Management Platform Documentation
  description: Documentation showcasing all available APIs
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
paths:
  /events:
    post:
      summary: Create a new event
      description: Creates a new event in the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                date:
                  type: string
                  format: date-time
                location:
                  type: string
              required:
                - title
                - description
                - date
                - location
      responses:
        '201':
          description: Event created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  date:
                    type: string
                    format: date-time
                  location:
                    type: string
        '400':
          description: Bad request or missing required fields
        '5xx':
          description: Server error
    get:
      summary: Get all events
      description: Retrieves all events from the database.
      responses:
        '200':
          description: Events retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string
                    date:
                      type: string
                      format: date-time
                    location:
                      type: string
        '5xx':
          description: Server error
  /events/{id}:
    get:
      summary: Get an event by its ID
      description: Retrieves an event from the database by its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Event retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  date:
                    type: string
                    format: date-time
                  location:
                    type: string
        '404':
          description: Event not found
        '5xx':
          description: Server error
    put:
      summary: Update an event by its ID
      description: Updates an event in the database by its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                date:
                  type: string
                  format: date-time
                location:
                  type: string
      responses:
        '200':
          description: Event updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  date:
                    type: string
                    format: date-time
                  location:
                    type: string
        '400':
          description: Bad request or missing required fields
        '5xx':
          description: Server error
    delete:
      summary: Delete an event by its ID
      description: Deletes an event from the database by its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Event deleted successfully
        '5xx':
          description: Server error
  /events/{id}/register:
    post:
      summary: Register an attendee to an event
      description: Registers an attendee to an event in the database.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Attendee registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '5xx':
          description: Server error
  /events/{id}/attendees:
    get:
      summary: Get all attendees of an event
      description: Retrieves all attendees of an event from the database by its ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Event attendees retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
        '5xx':
          description: Server error
components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        date:
          type: string
          format: date-time
        location:
          type: string
    Message:
      type: object
      properties:
        message:
          type: string
